-- ==============================================================================
-- CLÍNICA ROQUE - SCHEMA, FUNCIONES SQL Y POLÍTICAS RLS PARA SUPABASE
-- ==============================================================================
-- Copia y pega este script en: Supabase Dashboard -> SQL Editor -> New Query -> Run
-- ==============================================================================

-- 1. EXTENSIONES
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 2. TABLA DE COLAS / SALAS DE CONSULTA
CREATE TABLE IF NOT EXISTS public.colas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL,
    activa BOOLEAN DEFAULT TRUE NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- 3. TABLA DE TURNOS
CREATE TABLE IF NOT EXISTS public.turnos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cola_id BIGINT NOT NULL REFERENCES public.colas(id) ON DELETE CASCADE,
    numero VARCHAR(10) NOT NULL,
    estado VARCHAR(20) DEFAULT 'espera' NOT NULL CHECK (estado IN ('espera', 'llamado', 'atendido', 'descartado')),
    suscripcion_push JSONB DEFAULT NULL,
    preaviso_enviado BOOLEAN DEFAULT FALSE NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- 4. ÍNDICES DE RENDIMIENTO
CREATE INDEX IF NOT EXISTS idx_turnos_cola_estado ON public.turnos (cola_id, estado);
CREATE INDEX IF NOT EXISTS idx_turnos_cola_estado_created ON public.turnos (cola_id, estado, created_at ASC);
CREATE INDEX IF NOT EXISTS idx_turnos_cola_updated ON public.turnos (cola_id, updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_colas_activa ON public.colas (activa);

-- 5. TRIGGER AUTOMÁTICO PARA UPDATED_AT
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_turnos_updated_at ON public.turnos;
CREATE TRIGGER trg_turnos_updated_at
    BEFORE UPDATE ON public.turnos
    FOR EACH ROW
    EXECUTE FUNCTION public.set_updated_at();

-- 6. FUNCIÓN ATÓMICA DE LLAMADO DE TURNO (Evita Concurrencia con FOR UPDATE SKIP LOCKED)
CREATE OR REPLACE FUNCTION public.llamar_siguiente_turno(p_cola_id BIGINT)
RETURNS JSONB AS $$
DECLARE
    v_siguiente_turno RECORD;
    v_cuarto_turno RECORD;
    v_cola_nombre TEXT;
    v_resultado JSONB;
BEGIN
    -- Obtener el nombre de la sala
    SELECT nombre INTO v_cola_nombre FROM public.colas WHERE id = p_cola_id;
    
    -- Bloquear y obtener el primer turno en espera de forma atómica
    SELECT * INTO v_siguiente_turno
    FROM public.turnos
    WHERE cola_id = p_cola_id AND estado = 'espera'
    ORDER BY created_at ASC
    LIMIT 1
    FOR UPDATE SKIP LOCKED;

    -- Si no hay pacientes en espera
    IF v_siguiente_turno IS NULL THEN
        RETURN jsonb_build_object(
            'exito', false,
            'mensaje', 'No hay pacientes en espera'
        );
    END IF;

    -- Actualizar el estado del turno a 'llamado'
    UPDATE public.turnos
    SET estado = 'llamado', updated_at = NOW()
    WHERE id = v_siguiente_turno.id;

    -- Buscar el 4to paciente en espera para enviarle preaviso si aplica
    SELECT * INTO v_cuarto_turno
    FROM public.turnos
    WHERE cola_id = p_cola_id AND estado = 'espera' AND id != v_siguiente_turno.id
    ORDER BY created_at ASC
    OFFSET 2
    LIMIT 1;

    -- Construir respuesta para alertas push
    v_resultado := jsonb_build_object(
        'exito', true,
        'turno_llamado', jsonb_build_object(
            'id', v_siguiente_turno.id,
            'numero', v_siguiente_turno.numero,
            'cola_id', v_siguiente_turno.cola_id,
            'sala_nombre', v_cola_nombre,
            'suscripcion_push', v_siguiente_turno.suscripcion_push
        ),
        'turno_preaviso', CASE 
            WHEN v_cuarto_turno IS NOT NULL AND v_cuarto_turno.suscripcion_push IS NOT NULL AND NOT v_cuarto_turno.preaviso_enviado THEN
                jsonb_build_object(
                    'id', v_cuarto_turno.id,
                    'numero', v_cuarto_turno.numero,
                    'cola_id', v_cuarto_turno.cola_id,
                    'sala_nombre', v_cola_nombre,
                    'suscripcion_push', v_cuarto_turno.suscripcion_push
                )
            ELSE NULL
        END
    );

    -- Si hay preaviso, marcarlo como enviado
    IF v_cuarto_turno IS NOT NULL AND NOT v_cuarto_turno.preaviso_enviado THEN
        UPDATE public.turnos SET preaviso_enviado = true WHERE id = v_cuarto_turno.id;
    END IF;

    RETURN v_resultado;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 7. HABILITAR ROW LEVEL SECURITY (RLS) Y POLÍTICAS DE ACCESO
ALTER TABLE public.colas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.turnos ENABLE ROW LEVEL SECURITY;

-- Políticas para 'colas'
DROP POLICY IF EXISTS "Permitir lectura publica de colas" ON public.colas;
CREATE POLICY "Permitir lectura publica de colas" 
    ON public.colas FOR SELECT 
    USING (true);

DROP POLICY IF EXISTS "Permitir todo a usuarios autenticados en colas" ON public.colas;
CREATE POLICY "Permitir todo a usuarios autenticados en colas" 
    ON public.colas FOR ALL 
    TO authenticated 
    USING (true) 
    WITH CHECK (true);

-- Políticas para 'turnos'
DROP POLICY IF EXISTS "Permitir lectura publica de turnos" ON public.turnos;
CREATE POLICY "Permitir lectura publica de turnos" 
    ON public.turnos FOR SELECT 
    USING (true);

DROP POLICY IF EXISTS "Permitir insercion publica de turnos" ON public.turnos;
CREATE POLICY "Permitir insercion publica de turnos" 
    ON public.turnos FOR INSERT 
    WITH CHECK (true);

DROP POLICY IF EXISTS "Permitir actualizacion a autenticados en turnos" ON public.turnos;
CREATE POLICY "Permitir actualizacion a autenticados en turnos" 
    ON public.turnos FOR UPDATE 
    TO authenticated 
    USING (true) 
    WITH CHECK (true);

DROP POLICY IF EXISTS "Permitir actualizacion publica limitada de turnos" ON public.turnos;
CREATE POLICY "Permitir actualizacion publica limitada de turnos" 
    ON public.turnos FOR UPDATE 
    TO anon 
    USING (true) 
    WITH CHECK (true);

-- 8. HABILITAR PUBLICACIÓN REALTIME
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_publication_tables 
        WHERE pubname = 'supabase_realtime' AND tablename = 'turnos'
    ) THEN
        ALTER PUBLICATION supabase_realtime ADD TABLE public.turnos;
    END IF;
    
    IF NOT EXISTS (
        SELECT 1 FROM pg_publication_tables 
        WHERE pubname = 'supabase_realtime' AND tablename = 'colas'
    ) THEN
        ALTER PUBLICATION supabase_realtime ADD TABLE public.colas;
    END IF;
END $$;
